### ISSUE TITLE
FTP Fly with no root

### ISSUE THREAD

**Issue by mortiest** [owncloud/external#11]
I'm trying to setup an FTP server that has no permissions for directory creation.
Is there anyway to set the root as empty or / ?
I snooped around the code and I see that it's being set to / if not set, but either option always gives me error, even with standard ftp servers where I have full permissions.
statusMessage: "| League\Flysystem\FileNotFoundException: File not found at path:"

Also, not sure how exactly the ftp connection is being validated, but with that weird server I get green light as long as I input a directory, even tho no directory exists, but that creates other sort of problems when syncing files and navigating the UI.

**Comment by PVince81** [comment]
this repository is only about external sites, for adding clickable links that open inside an iframe.

for the FTP external storage, go to https://github.com/owncloud/files_external_ftp
