### ISSUE TITLE
release to marketplace?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/external#5]
@pvince81

**Comment by PVince81** [comment]
had a chat with @pmaier1  and this is low prio

**Comment by PVince81** [comment]
if we don't release this to marketplace, we might need to maintain both master and stable10 branches.

or adjust the release script to always use master

thoughts ? @DeepDiver1975 @patrickjahns

**Comment by pmaier1** [comment]
We should release it to Marketplace but I would like to do that after 10.0.10 to have enough time for the info.xml fun.

**Comment by DeepDiver1975** [comment]
The stable10 branch in in here and it used by the release script. Also the fix regarding the icons in in stable10 https://github.com/owncloud/external/commit/7881cdd4b2d5d95ab5b684f1839aefc8eabddc89

So no issues in keeping this as is for the time being

**Comment by DeepDiver1975** [comment]
feel free to reopen if this will ever be of interest
