### ISSUE TITLE
Rename repro name from "external" to "external_sites"

### ISSUE THREAD

**Issue by mmattel** [owncloud/external#7]
repro name not very descriptive

@PVince81 @DeepDiver1975 @phil-davis @patrickjahns

**Comment by DeepDiver1975** [comment]
:-1: the repo name has to be identical to the app id. we cannot easily rename the app.

**Comment by mmattel** [comment]
This app has not been released
Therefore nobody knows the name fromthe marketplace and has an issue when it will be renamed here
The name ``external`` is the worst of the bad and ugly choices and only makes bad impressions

(btw, we should behave and present ourselfs professional or??)

The rest is just a bit of work to set it up and would make things good again :copyright: donny

FYI @hurradieweltgehtunter marketing should be involved

**Comment by DeepDiver1975** [comment]
This app is one of the oldest apps we have in the releases - since owncloud 4 or even earlier.
This app was living in the apps repo for a long time https://github.com/owncloud/apps/commit/0eb47bf02ff9119e8835fa2e79a2de0953219ccb

**Comment by mmattel** [comment]
but not as an app from the marketplace, this is the breaking line
you must make at one point a cut and get off the legacy
renaming is not a showstopper
all existing installations will have to get rid of the git clone and install from marketplace anyways

**Comment by DeepDiver1975** [comment]
to be decided in the scope of #5 

as of now this will be part of the 10.0.x server release and has to stay this way ...

in the scope of releasing it to the marketplace only renaming is quite valid -. yes

**Comment by DeepDiver1975** [comment]
feel free to reopen if this will ever be of interest
